spring:
  freemarker:
    allow-request-override: true
    content-type: application/json;charset=utf-8
    template-loader-path: /templates/
    enabled: true
  groovy:
    template:
      content-type: text/html
  http:
    converters:
      preferred-json-mapper: jackson
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0B
      max-file-size: 1MB
      max-request-size: 10MB
      location: /tmp/
      resolve-lazily: false
logging:
  config: classpath:logback-boot.xml
server:
  port: 8080